# Collects CollectorA and HBase into containers and combines it

services:
  namenode:
    extends:
      file: ./docker/hbase/docker-compose-standalone.yml
      service: namenode
  datanode:
    extends:
      file: ./docker/hbase/docker-compose-standalone.yml
      service: datanode
  resourcemanager:
    extends:
      file: ./docker/hbase/docker-compose-standalone.yml
      service: resourcemanager
  nodemanager1:
    extends:
      file: ./docker/hbase/docker-compose-standalone.yml
      service: nodemanager1
  historyserver:
    extends:
      file: ./docker/hbase/docker-compose-standalone.yml
      service: historyserver
  hbase:
    extends:
      file: ./docker/hbase/docker-compose-standalone.yml
      service: hbase

  collectora:
    container_name: collectora
    build: ./docker/image
    command: bash -c "chmod +x ${COLLECTORA_DIR}/scripts/*
      && tail -f /dev/null"
    volumes:
      - ./gradle:${COLLECTORA_DIR}/gradle
      - ./scripts:${COLLECTORA_DIR}/scripts
      - ./src:${COLLECTORA_DIR}/src
      - ./build.gradle:${COLLECTORA_DIR}/build.gradle
      - ./gradlew:${COLLECTORA_DIR}/gradlew
      - ./gradlew.bat:${COLLECTORA_DIR}/gradlew.bat
      - ./settings.gradle:${COLLECTORA_DIR}/settings.gradle
      - ./build:${COLLECTORA_DIR}/build
    networks:
      - backend
    ports:
      - "443:8080"
      - "2181:2181"
      - "8085:8080"
    depends_on:
      - hbase

networks:
  backend:
    driver: bridge
