# Collects CollectorA and HBase into containers and combines it

services:
  hbase:
    container_name: hbase
    build: ./docker/hbase
    command: bash -c "start-hbase.sh; hbase shell && tail -f /dev/null"
    networks:
      - backend
    ports:
      - "2181:2181"
      - "16000:16000"

  collectora:
    container_name: collectora
    build: ./docker/image
    command: bash -c "chmod +x ${COLLECTORA_DIR}/scripts/*
      && tail -f /dev/null"
    volumes:
      - ./gradle:${COLLECTORA_DIR}/gradle
      - ./scripts:${COLLECTORA_DIR}/scripts
      - ./src:${COLLECTORA_DIR}/src
      - ./build.gradle:${COLLECTORA_DIR}/build.gradle
      - ./gradlew:${COLLECTORA_DIR}/gradlew
      - ./gradlew.bat:${COLLECTORA_DIR}/gradlew.bat
      - ./settings.gradle:${COLLECTORA_DIR}/settings.gradle
    networks:
      - backend
    ports:
      - "8081:8080"
    depends_on:
      - hbase

networks:
  backend:
    driver: bridge
