# Collects CollectorA and HBase into containers and combines it

services:
  hbase:
    image: dajobe/hbase
    hostname: hbase
    build: .
    volumes:
      - $PWD/hbase-data:/data
      - $PWD/hbase-site.xml:/opt/hbase/conf/hbase-site.xml
    ports:
      - 8080:8080   # REST API
      - 9090:9090   # Thrift API
      - 16000:16000 # Master API
      - 16010:16010 # Master UI
      - 16020:16020 # Regionserver API
      - 16030:16030 # Regionserver UI
