###
# build CollectorA
###
FROM ubuntu:22.04
WORKDIR /root

RUN apt update && apt install -y \
    vim   \
    curl  \
    wget  \
    openjdk-21-jdk \
    tree  \
    htop  \
    git   \
    net-tools
